In [25]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [26]:
df=pd.read_csv("nlp_train.csv")

In [27]:
df

text  target  \
0      I was wondering if anyone out there could enli...       7   
1      A fair number of brave souls who upgraded thei...       4   
2      well folks, my mac plus finally gave up the gh...       4   
3      \nDo you have Weitek's address/phone number?  ...       1   
4      From article <C5owCB.n3p@world.std.com>, by to...      14   
...                                                  ...     ...   
11309  DN> From: nyeda@cnsvax.uwec.edu (David Nye)\nD...      13   
11310  I have a (very old) Mac 512k and a Mac Plus, b...       4   
11311  I just installed a DX2-66 CPU in a clone mothe...       3   
11312  \nWouldn't this require a hyper-sphere.  In 3-...       1   
11313  Stolen from Pasadena between 4:30 and 6:30 pm ...       8   

                       category  
0                     rec.autos  
1         comp.sys.mac.hardware  
2         comp.sys.mac.hardware  
3                 comp.graphics  
4                     sci.space  
...                         ...  
11309                   sci.med  
11310     comp.sys.mac.hardware  
11311  comp.sys.ibm.pc.hardware  
11312             comp.graphics  
11313           rec.motorcycles  

[11314 rows x 3 columns]

In [28]:
df['category'].unique()

array(['rec.autos', 'comp.sys.mac.hardware', 'comp.graphics', 'sci.space',
       'talk.politics.guns', 'sci.med', 'comp.sys.ibm.pc.hardware',
       'comp.os.ms-windows.misc', 'rec.motorcycles', 'talk.religion.misc',
       'misc.forsale', 'alt.atheism', 'sci.electronics', 'comp.windows.x',
       'rec.sport.hockey', 'rec.sport.baseball', 'soc.religion.christian',
       'talk.politics.mideast', 'talk.politics.misc', 'sci.crypt'],
      dtype=object)

In [29]:
print(df.iloc[0,0])

I was wondering if anyone out there could enlighten me on this car I saw
the other day. It was a 2-door sports car, looked to be from the late 60s/
early 70s. It was called a Bricklin. The doors were really small. In addition,
the front bumper was separate from the rest of the body. This is 
all I know. If anyone can tellme a model name, engine specs, years
of production, where this car is made, history, or whatever info you
have on this funky looking car, please e-mail.


In [30]:
df.iloc[0,2]

'rec.autos'

In [31]:
print(df.iloc[1,0])

A fair number of brave souls who upgraded their SI clock oscillator have
shared their experiences for this poll. Please send a brief message detailing
your experiences with the procedure. Top speed attained, CPU rated speed,
add on cards and adapters, heat sinks, hour of usage per day, floppy disk
functionality with 800 and 1.4 m floppies are especially requested.

I will be summarizing in the next two days, so please add to the network
knowledge base if you have done the clock upgrade and haven't answered this
poll. Thanks.


In [32]:
df.iloc[1,2]

'comp.sys.mac.hardware'

In [33]:
x="you won lottery"
p("spam"|"you won lottery")=

SyntaxError: cannot assign to function call (1763481560.py, line 2)

In [34]:
#countVecctorizer
d1="I love programming"
d2="programming is intresting"
d3="I love pizza very very much"
# vocab={I,love,programming,is,intresting,love,much}
# d1=[1,1,1,0,0,0,0,0]
# d2=[0,0,1,1,1,0,0,0]
# d3=[1,1,0,0,0,1,2,1]

In [35]:
from sklearn.feature_extraction.text import CountVectorizer
document=[d1,d2,d3]
vectorizer=CountVectorizer()
x=vectorizer.fit_transform(document)

In [36]:
vectorizer.fit_transform(document)
print(vectorizer.vocabulary_)

{'love': 2, 'programming': 5, 'is': 1, 'intresting': 0, 'pizza': 4, 'very': 6, 'much': 3}


In [37]:
print(x.toarray())

[[0 0 1 0 0 1 0]
 [1 1 0 0 0 1 0]
 [0 0 1 1 1 0 2]]


In [38]:
train_df=pd.read_csv("nlp_train.csv")
test_df=pd.read_csv("nlp_test.csv")


In [39]:
train_df.shape

(11314, 3)

In [43]:
test_df.shape

(7532, 3)

In [44]:
train_df.head(5)

text  target  \
0  I was wondering if anyone out there could enli...       7   
1  A fair number of brave souls who upgraded thei...       4   
2  well folks, my mac plus finally gave up the gh...       4   
3  \nDo you have Weitek's address/phone number?  ...       1   
4  From article <C5owCB.n3p@world.std.com>, by to...      14   

                category  
0              rec.autos  
1  comp.sys.mac.hardware  
2  comp.sys.mac.hardware  
3          comp.graphics  
4              sci.space

In [45]:
test_df.head(5)

text  target  \
0  I am a little confused on all of the models of...       7   
1  I'm not familiar at all with the format of the...       5   
2                                \nIn a word, yes.\n       0   
3  \nThey were attacking the Iraqis to drive them...      17   
4  \nI've just spent two solid months arguing tha...      19   

                category  
0              rec.autos  
1         comp.windows.x  
2            alt.atheism  
3  talk.politics.mideast  
4     talk.religion.misc

In [46]:
#3.
train_df.iloc[:,1]

0         7
1         4
2         4
3         1
4        14
         ..
11309    13
11310     4
11311     3
11312     1
11313     8
Name: target, Length: 11314, dtype: int64

In [47]:
test_df.iloc[:,1]

0        7
1        5
2        0
3       17
4       19
        ..
7527    14
7528     4
7529     9
7530     6
7531    15
Name: target, Length: 7532, dtype: int64

In [48]:
train_df['category'].value_counts()

category
rec.sport.hockey            600
soc.religion.christian      599
rec.motorcycles             598
rec.sport.baseball          597
sci.crypt                   595
sci.med                     594
rec.autos                   594
sci.space                   593
comp.windows.x              593
comp.os.ms-windows.misc     591
sci.electronics             591
comp.sys.ibm.pc.hardware    590
misc.forsale                585
comp.graphics               584
comp.sys.mac.hardware       578
talk.politics.mideast       564
talk.politics.guns          546
alt.atheism                 480
talk.politics.misc          465
talk.religion.misc          377
Name: count, dtype: int64

In [49]:
print(train_df['target'].nunique())

20


In [51]:
train_df['category'].value_counts()

category
rec.sport.hockey            600
soc.religion.christian      599
rec.motorcycles             598
rec.sport.baseball          597
sci.crypt                   595
sci.med                     594
rec.autos                   594
sci.space                   593
comp.windows.x              593
comp.os.ms-windows.misc     591
sci.electronics             591
comp.sys.ibm.pc.hardware    590
misc.forsale                585
comp.graphics               584
comp.sys.mac.hardware       578
talk.politics.mideast       564
talk.politics.guns          546
alt.atheism                 480
talk.politics.misc          465
talk.religion.misc          377
Name: count, dtype: int64

In [52]:
print(test_subset['target'].nunique())

NameError: name 'test_subset' is not defined

In [53]:
# print subset of all categories alt.atheism,comp.graphics,sci.space
train_subset = train_df[train_df['category'].isin(['alt.atheism', 'comp.graphics', 'sci.space'])]
print(train_subset)


                                                    text  target  \
3      \nDo you have Weitek's address/phone number?  ...       1   
4      From article <C5owCB.n3p@world.std.com>, by to...      14   
13     \n   {Description of "External Tank" option fo...      14   
15     \nDon't be so sure.  Look what happened to Jap...       0   
16     \nI certainly do use it whenever I have to do ...       1   
...                                                  ...     ...   
11275  \nThis sounds like another of Ali AbuTaha's 57...      14   
11276  A new alternative to Scouting for those "unacc...       0   
11286  \n\n\n\n\nThe HGA isn't all that reflective in...      14   
11289  I have a Diamond Speedstar 24X board that I wa...       1   
11312  \nWouldn't this require a hyper-sphere.  In 3-...       1   

            category  
3      comp.graphics  
4          sci.space  
13         sci.space  
15       alt.atheism  
16     comp.graphics  
...              ...  
11275      sci.space  

In [181]:
test_subset = test_df[test_df['category'].isin(['alt.atheism', 'comp.graphics', 'sci.space'])]
print(test_subset)

                                                   text  target       category
2                                   \nIn a word, yes.\n       0    alt.atheism
9     :  \n: well, i have lots of experience with sc...       1  comp.graphics
14    \nProbably because it IS rape.\n\n\nSo nothing...       0    alt.atheism
17    Hello,\ni'm interested in those devices too.\n...       1  comp.graphics
20    This is an invitation to send articles to the ...       1  comp.graphics
...                                                 ...     ...            ...
7488  \n\namen.. I too have learned by example, spec...       1  comp.graphics
7492  \n: I agree, I had a hard feeling not believin...       0    alt.atheism
7496  \n\nYes a flotation tank, combined with florid...      14      sci.space
7505  Archive-name: atheism/overview\nAlt-atheism-ar...       0    alt.atheism
7527  \n   Henry, if I read you correctly, you may b...      14      sci.space

[1102 rows x 3 columns]


In [54]:
test_subset['target'].value_counts()

NameError: name 'test_subset' is not defined

In [183]:
#9
train_subset['category'].unique()

array(['comp.graphics', 'sci.space', 'alt.atheism'], dtype=object)

In [184]:
#10
print(train_subset.iloc[4])

text        \nI certainly do use it whenever I have to do ...
target                                                      1
category                                        comp.graphics
Name: 16, dtype: object


In [185]:
print(train_subset.iloc[4,0])


I certainly do use it whenever I have to do TIFF, and it usually works
very well.  That's not my point.  I'm >philosophically< opposed to it
because of its complexity.

This complexity has led to some programs' poor TIFF writers making
some very bizarre files, other programs' inability to load TIFF
images (though they'll save them, of course), and a general
inability to interchange images between different environments
despite the fact they all think they understand TIFF.

As the saying goes, "It's not me I'm worried about- it's all the
abuse of TIFF over the years, and I chalk it all up to the immense (and
unnecessary) complexity of the format.

In the words of the TIFF 5.0 spec, Appendix G, page G-1 (capitalized
emphasis mine):

"The only problem with this sort of success is that TIFF was designed
to be powerful and flexible, at the expense of simplicity.  It takes a
fair amount of effort to handle all the options currently defined in
this specification (PROBABLY NO APPLICATION DOES

In [186]:
train_subset.iloc[4]['text']

'\nI certainly do use it whenever I have to do TIFF, and it usually works\nvery well.  That\'s not my point.  I\'m >philosophically< opposed to it\nbecause of its complexity.\n\nThis complexity has led to some programs\' poor TIFF writers making\nsome very bizarre files, other programs\' inability to load TIFF\nimages (though they\'ll save them, of course), and a general\ninability to interchange images between different environments\ndespite the fact they all think they understand TIFF.\n\nAs the saying goes, "It\'s not me I\'m worried about- it\'s all the\nabuse of TIFF over the years, and I chalk it all up to the immense (and\nunnecessary) complexity of the format.\n\nIn the words of the TIFF 5.0 spec, Appendix G, page G-1 (capitalized\nemphasis mine):\n\n"The only problem with this sort of success is that TIFF was designed\nto be powerful and flexible, at the expense of simplicity.  It takes a\nfair amount of effort to handle all the options currently defined in\nthis specification

In [187]:
#11
print("",train_subset.shape)

 (1657, 3)


In [188]:
print(train_subset.shape[0])

1657


In [189]:
print(train_subset['target'].nunique())

3


In [190]:
print(test_subset['target'].nunique())

3


In [196]:
train_subset['text'].isnull().sum()

33

In [198]:
train_subset=train_subset.dropna(subset='text')

In [199]:
train_subset['text'].isnull().sum()

0

In [201]:
#13
from sklearn.feature_extraction.text import CountVectorizer

vectorizer=CountVectorizer()
x=vectorizer.fit_transform(train_subset['text'])

In [204]:
print(vectorizer.vocabulary_)

{'do': 7674, 'you': 23500, 'have': 10608, 'weitek': 22974, 'address': 2502, 'phone': 16244, 'number': 15161, 'like': 13123, 'to': 21402, 'get': 9999, 'some': 19757, 'information': 11628, 'about': 2293, 'this': 21239, 'chip': 5265, 'from': 9677, 'article': 3405, 'c5owcb': 4743, 'n3p': 14672, 'world': 23255, 'std': 20196, 'com': 5666, 'by': 4729, 'tombaker': 21437, 'tom': 21434, 'baker': 3820, 'my': 14646, 'understanding': 22014, 'is': 12065, 'that': 21151, 'the': 21152, 'expected': 8812, 'errors': 8541, 'are': 3326, 'basically': 3906, 'known': 12640, 'bugs': 4634, 'in': 11428, 'warning': 22860, 'system': 20819, 'software': 19721, 'things': 21224, 'checked': 5213, 'don': 7739, 'right': 18388, 'values': 22384, 'yet': 23483, 'because': 3971, 'they': 21211, 'aren': 3329, 'set': 19189, 'till': 21343, 'after': 2665, 'launch': 12854, 'and': 3023, 'suchlike': 20511, 'rather': 17572, 'than': 21147, 'fix': 9311, 'code': 5556, 'possibly': 16670, 'introduce': 11936, 'new': 14870, 'just': 12414, 'te

In [213]:
x.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [220]:
print(vectorizer.get_feature_names_out())  

['00' '000' '0000' ... 'zware' 'zwarte' 'zyxel']


In [221]:
train_subset.head()

text  target       category
3   \nDo you have Weitek's address/phone number?  ...       1  comp.graphics
4   From article <C5owCB.n3p@world.std.com>, by to...      14      sci.space
13  \n   {Description of "External Tank" option fo...      14      sci.space
15  \nDon't be so sure.  Look what happened to Jap...       0    alt.atheism
16  \nI certainly do use it whenever I have to do ...       1  comp.graphics